AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates the data S3 bucket and the skeleton Lambda function.'

Resources:
  CsvDataBucket:
    Type: 'AWS::S3::Bucket'
    DependsOn:
      - LambdaInvokePermission
    Properties:
      BucketName: 'daily-brew-csv-data-bucket'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt ETLLambda.Arn

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2010-10-12'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

#The Skeleton ETL Lambda Function
  ETLLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'daily-brew-etl-lambda'
      Runtime: python3.11
      Handler: lambda_handler.lambda_handler   
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              print("hello team")
              return {'statusCode': 200}

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref ETLLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::daily-brew-csv-data-bucket'

Outputs:
  LambdaArn:
    Description: 'The ARN of the skeleton ETL Lambda function'
    Value: !GetAtt ETLLambda.Arn
