AWSTemplateFormatVersion: "2010-09-09"
Description: Deployment bucket for Lambda code

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: espresso-yourself-deployment-bucket
